### ISSUE TITLE
Whether the edge node deployment application container supports multiple replicas.

### ISSUE THREAD

**Issue by teafull** [superedge/superedge#17]
Whether the edge node deployment application container supports multiple replicas.

```
apiVersion: superedge.io/v1
kind: DeploymentGrid
metadata:
  name: deploymentgrid-demo
  namespace: default
spec:
  replicas: 2 # Can it be used here?
  gridUniqKey: zone
  template:
    selector:
      matchLabels:
        appGrid: nginx
    template:
      metadata:
        labels:
          appGrid: nginx
      spec:
        containers:
          - name: nginx
            image: nginx:1.7.9
            ports:
              - containerPort: 80
```
