### ISSUE TITLE
[Question]应用程序如何访问ServiceGrid

### ISSUE THREAD

**Issue by tianxin8206** [superedge/superedge#219]
部署ServiceGrid后，程序无法访问，报错信息如下图：
![image](https://user-images.githubusercontent.com/32237514/129542231-8a8e50b6-faaa-47f9-80c3-2217f8024139.png)

数据库部署yaml：
```yaml
---
apiVersion: superedge.io/v1
kind: DeploymentGrid
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: database
  name: database
  namespace: mkwszc
spec:
  gridUniqKey: zone
  progressDeadlineSeconds: 600
  template:
    replicas: 1
    selector:
      matchLabels:
        k8s.kuboard.cn/layer: db
        k8s.kuboard.cn/name: database
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s.kuboard.cn/layer: db
          k8s.kuboard.cn/name: database
      spec:
        containers:
          - args:
              - mysqld
              - '--character-set-server=utf8mb4'
              - '--collation-server=utf8mb4_general_ci'
              - '--default_authentication_plugin=mysql_native_password'
              - '--explicit_defaults_for_timestamp=true'
              - '--lower_case_table_names=1'
              - '--max_allowed_packet=128M'
              - '--max_connections=500'
              - >-
                --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO
            env:
              - name: MYSQL_ROOT_PASSWORD
                value: '123456'
            image: 'mysql:8.0.25'
            imagePullPolicy: IfNotPresent
            name: mysql
            ports:
              - containerPort: 3306
                name: mysql
                protocol: TCP
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: volume-mysql
        dnsPolicy: ClusterFirst
        nodeSelector:
          project: mkwszc
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - hostPath:
              path: /var/lib/mysql
              type: DirectoryOrCreate
            name: volume-mysql

---
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: database
  name: database
  namespace: mkwszc
spec:
  gridUniqKey: zone
  externalTrafficPolicy: Cluster
  template:
    ports:
      - name: mysql
        nodePort: 3306
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      k8s.kuboard.cn/layer: db
      k8s.kuboard.cn/name: database
  sessionAffinity: None
  type: NodePort
```

应用程序部署：
```yaml
---
apiVersion: superedge.io/v1
kind: DeploymentGrid
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: webapp
  name: webapp
  namespace: mkwszc
spec:
  gridUniqKey: zone
  progressDeadlineSeconds: 600
  template:
    replicas: 1
    selector:
      matchLabels:
        k8s.kuboard.cn/layer: svc
        k8s.kuboard.cn/name: webapp
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s.kuboard.cn/layer: svc
          k8s.kuboard.cn/name: webapp
      spec:
        containers:
          - image: 'webapp:latest'
            imagePullPolicy: IfNotPresent
            name: webapp
            ports:
              - containerPort: 8061
                name: webapp
                protocol: TCP
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        nodeSelector:
          project: mkwszc
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30

---
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  annotations: {}
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: webapp
  name: webapp
  namespace: mkwszc
spec:
  gridUniqKey: zone
  externalTrafficPolicy: Cluster
  template:
    ports:
      - name: webapp
        nodePort: 8061
        port: 8061
        protocol: TCP
        targetPort: 8061
    selector:
      k8s.kuboard.cn/layer: svc
      k8s.kuboard.cn/name: webapp
  sessionAffinity: None
  type: NodePort
```

数据库连接字符串：
Data Source=database;Port=3306;User ID=root;Password=123456;Initial Catalog=jy_eadp_mkwszc;Charset=utf8mb4;SslMode=none;Min pool size=1
