### ISSUE TITLE
SEP: ServiceGroup StatefulSetGrid Design Specification

### ISSUE THREAD

**Issue by duyanghao** [superedge/superedge#26]
This is my initial design of ServiceGroup StatefulSetGrid as below:

![image](https://user-images.githubusercontent.com/12867714/104675768-1141e300-5721-11eb-9956-24aa3f97b70c.png)

StatefulSetGrid custom resource samples below:

```yaml
apiVersion: superedge.io/v1
kind: StatefulSetGrid
metadata:
  name: statefulsetgrid-demo
  namespace: default
spec:
  gridUniqKey: zone1
  template:
    selector:
      matchLabels:
        appGrid: nginx # has to match .spec.template.metadata.labels
    serviceName: "servicegrid-demo-svc"
    replicas: 3 # by default is 1
    template:
      metadata:
        labels:
          appGrid: nginx # has to match .spec.selector.matchLabels
      spec:
        terminationGracePeriodSeconds: 10
        containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: www
            mountPath: /usr/share/nginx/html
    volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
```

ServiceGrid stays unchanged and samples below:

```yaml
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  name: servicegrid-demo
  namespace: default
spec:
  gridUniqKey: zone1
  template:
    selector:
      appGrid: nginx
    ports:
    - port: 80
      name: web
    clusterIP: None                                                       
```

this design works as follows:
1. StatefulSetGrid will generate relevant Kubernetes statefulset workload for each of nodeunit as DeploymentGrid does(i.e. {StatefulSetGrid}-{NodeUnit})
2. StatefulSet headless service will be access by domains constructed by `{StatefulSetGrid}-{0..N-1}.{ServiceGrid}-svc.
default.svc.cluster.local` which corresponds to actual statefulset workload `{StatefulSetGrid}-{NodeUnit}-{0..N-1}.{ServiceGrid}-svc.default.svc.cluster.local`, aiming to block the difference of nodeunits. 
3. StatefulSet normal clusterIP service access stays unchanged by using achieved service topology.(i.e. {ServiceGrid}-svc)
