### ISSUE TITLE
ServiceGroup与nodeSelector同时使用时pod调度异常

### ISSUE THREAD

**Issue by tianxin8206** [superedge/superedge#301]
**What happened**:

ServiceGroup与nodeSelector同时使用时，第一个具备条件的节点，pod调度、启动正常，当第二个节点添加node与nodetype标签后，会影响到第一个节点的pod，如下图
![pending](https://user-images.githubusercontent.com/32237514/145947739-28c7b12c-1fdd-4534-bb98-8d74306e7339.png)
同时，第二个节点的pod会出现重启行为，events如下图
![start-stop](https://user-images.githubusercontent.com/32237514/145947845-7907795a-e090-4356-ad18-0b7462021bc4.png)

**What you expected to happen**:

ServiceGroup与nodeSelector可同时使用

**How to reproduce it (as minimally and precisely as possible)**:
我的yaml:
```yaml
---
apiVersion: superedge.io/v1
kind: StatefulSetGrid
metadata:
  annotations:
    k8s.kuboard.cn/displayName: DataService
  labels:
    appGrid: dependency
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: dependency
  name: dependency
  namespace: mkwszc
spec:
  gridUniqKey: node
  template:
    podManagementPolicy: OrderedReady
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        appGrid: dependency
        k8s.kuboard.cn/layer: db
        k8s.kuboard.cn/name: dependency
    serviceName: dependency
    template:
      metadata:
        labels:
          appGrid: dependency
          k8s.kuboard.cn/layer: db
          k8s.kuboard.cn/name: dependency
      spec:
        containers:
          - args:
              - mysqld
              - '--character-set-server=utf8mb4'
              - '--collation-server=utf8mb4_general_ci'
              - '--default_authentication_plugin=mysql_native_password'
              - '--explicit_defaults_for_timestamp=true'
              - '--lower_case_table_names=1'
              - '--max_allowed_packet=128M'
              - '--max_connections=500'
              - '--sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ERROR_FOR_DIVISION_BY_ZERO'
              - '--skip-host-cache'
              - '--skip-name-resolve'
            env:
              - name: MYSQL_USER
                value: wsuser
              - name: MYSQL_PASSWORD
                value: JY@pass01!wsuser
              - name: MYSQL_ROOT_PASSWORD
                value: JY@pass01!_mysql
              - name: LANG
                value: C.UTF-8
              - name: TZ
                value: Asia/Shanghai
            image: 'mysql:8.0.26'
            imagePullPolicy: IfNotPresent
            name: mysql
            ports:
              - containerPort: 3306
                name: mysql
                protocol: TCP
            resources:
              limits:
                cpu: '2'
                memory: 2Gi
              requests:
                cpu: 500m
                memory: 1Gi
            volumeMounts:
              - mountPath: /var/lib/mysql
                name: volume-mysql
        restartPolicy: Always
        nodeSelector:
          nodetype: db
        volumes:
          - hostPath:
              path: /var/lib/mysql/data
              type: DirectoryOrCreate
            name: volume-mysql

---
apiVersion: superedge.io/v1
kind: ServiceGrid
metadata:
  annotations: {}
  labels:
    appGrid: dependency
    k8s.kuboard.cn/layer: db
    k8s.kuboard.cn/name: dependency
  name: dependency
  namespace: mkwszc
spec:
  gridUniqKey: node
  template:
    externalTrafficPolicy: Cluster
    ports:
      - name: mysql
        nodePort: 3306
        port: 3306
        protocol: TCP
        targetPort: 3306
    selector:
      appGrid: dependency
      k8s.kuboard.cn/layer: db
      k8s.kuboard.cn/name: dependency
    sessionAffinity: None
    type: NodePort
```
**Anything else we need to know?**:

**Environment**:
- SuperEdge version: 0.6.0
- Kubernetes version (use `kubectl version`): 1.18.2
- OS (e.g. `cat /etc/os-release`): centos 7.9
- Kernel (e.g. `uname -a`): 5.15
- Hardware configuration (e.g. `lscpu`) 16
- Go Version (e.g. `go version`)
- Others:
