### ISSUE TITLE
Create a class of Nodeunit based on node label key 

### ISSUE THREAD

**Issue by attlee-wang** [superedge/superedge#329]
**What would you like to be added/modified**:

Create a class of Nodeunit based on node label key 

such as:
```
apiVersion: site.superedge.io/v1
kind: NodeGroup
metadata:
  name: nodegroup-demo
spec:
  autofindnodekeys: 
  - vpc-key
  - ssd-key
  workload:
  - name: demo
    type: Deployment
```

**Why is this needed**:

A class of NodeUnits can be created in batches
