### ISSUE TITLE
[Edge DNS] dns for edge

### ISSUE THREAD

**Issue by Beckham007** [superedge/superedge#77]
It is usually to create a CoreDNS `Deployment` for running CoreDNS on Kubernetes cluster, [coredns.yaml](https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed)

In edge computing, it is hard to visit `kube-dns` service for network reason. 
We can deploy  CoreDNS by `DaemonSet` with hostnetwork, and then modify `--cluster-dns` of kubelet to hostIP.

1. apply the following coredns-daemonset.yaml
`kubectl apply -f coredns-daemonset.yaml`
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coredns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: "CoreDNS"
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: coredns
          image: coredns/coredns:1.6.7
          imagePullPolicy: IfNotPresent
          args: [ "-conf", "/etc/coredns/Corefile" ]
          resources:
            limits:
              memory: 170Mi
            requests:
              cpu: 100m
              memory: 70Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/coredns
              readOnly: true
            - name: tmp
              mountPath: /tmp
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 9153
              name: metrics
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_BIND_SERVICE
              drop:
                - all
            readOnlyRootFilesystem: true
      dnsPolicy: Default
      hostNetwork: true
      volumes:
        - name: config-volume
          configMap:
            name: coredns
            items:
              - key: Corefile
                path: Corefile
        - name: tmp
          hostPath:
            path: /tmp
```

2. delete CoreDNS deployment
`kubectl delete deployment coredns -nkube-system`

3. update kubelet config
